---
title: 'Model call record'
output: pdf_document
classoption: landscape
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y %h:%m')`"
---

Check package version.

```{r}
packageVersion('ALFAM2')
```

Check values of pars03.

```{r}
pars03[order(names(pars03))]
```

Compare to:

```{r}
alfam2pars03[order(names(alfam2pars03))]
```

Run model with par set 3

```{r}
pr3 <- alfam2(dat, app.name = 'tan.app', time.name = 'ct', time.incorp = 'time.incorp',
              group = 'sida', pars = pars03, flatout = TRUE)
#pr3 <- alfam2(dat, app.name = 'tan.app', time.name = 'ct', time.incorp = 'time.incorp',
#              group = 'sida', pars = alfam2pars03, flatout = TRUE)
setDT(pr3)
```

Run with par set 2

```{r}
pr2 <- alfam2(dat, app.name = 'tan.app', time.name = 'ct', time.incorp = 'time.incorp',
              group = 'sida', pars = alfam2pars02, flatout = TRUE)
setDT(pr2)
```

Run with par set 1

```{r}
pr1 <- alfam2(dat, app.name = 'tan.app', time.name = 'ct', time.incorp = 'time.incorp',
              group = 'sida', pars = alfam2pars01, flatout = TRUE)
setDT(pr1)
```

ALFAM(1) model

```{r}
dat[, app.mthd.bsth := 0]
dat[app.mthd == 'bsth', app.mthd.bsth := 1]
dat[, incorp.none := 0]
dat[incorp == 'none', incorp.none := 1]
dat[, meas.tech.mm := 1]
pr0 <- ALFAM1mod(as.data.frame(dat), time.name = 'ct', group = 'sida')
pr0 <- as.data.table(pr0)
pr0[er > 1, er := 1]
```


