---
title: 'Summary of ALFAM2 database'
author: 'Sasha D. Hafner'
date: "`r format(Sys.time(), '%H:%M - %d %B, %Y')`"
---

```{r}
dim(pdat)
table(pdat[, sub.period])
table(pdat[, corr.period])
table(pdat[, .(country, corr.period)])
table(pdat[, .(country, sub.period)])
table(pdat[, .(meas.tech2, sub.period)])
table(pdat[, .(sub.period, !is.na(e.rel.final) & e.rel.final > 1.5)])
table(pdat[, .(sub.period, !is.na(e.rel.final) & e.rel.final > 2)])
table(pdat[, .(sub.period, is.na(e.rel.final))])
```

```{r}
table(pdat[, .(treat.nm, sub.period)])

table(pdat$treat.nm, exclude = NULL)

table(pdat[, .(period.nm, ct.max > 72)]) / matrix(rep(table(pdat[, .(period.nm)]), 2), ncol = 2)
table(pdat[, .(period.nm, ct.max > 96)]) / matrix(rep(table(pdat[, .(period.nm)]), 2), ncol = 2)
table(pdat[, .(period.nm, ct.max > 168)]) / matrix(rep(table(pdat[, .(period.nm)]), 2), ncol = 2)
```


```{r}
table(pdat[, .(sub.period, ct.max > 72)]) / matrix(rep(table(pdat[, .(sub.period)]), 2), ncol = 2)
table(pdat[, .(sub.period, ct.max > 96)]) / matrix(rep(table(pdat[, .(sub.period)]), 2), ncol = 2)
table(pdat[, .(sub.period, ct.max > 168)]) / matrix(rep(table(pdat[, .(sub.period)]), 2), ncol = 2)
```

New data specifically

```{r}
x <- pdat[sub.period == 3, ]
table(x[, .(inst, treat.nm)])
table(x[, .(inst)])
table(pdat[, .(inst)])
table(pdat[, .(institute)])
table(x[, .(institute)])
table(pdat[, .(inst, treat.nm)])
table(pdat[, .(inst, corr.period)])
```

Johanna's wind tunnel results

```{r}
table(pdat[, .(inst, meas.tech2) ])
table(pdat[, .(institute, meas.tech2) ])
```

```{r}
x <- pdat[inst == 205, ]
table(x[, .(sub.period, meas.tech2)])
```

```{r}
x <- pdat[inst == 205 & meas.tech2 == 'wt', ]
table(x[, .(sub.period, app.mthd)])
```

```{r}
x <- pdat[inst == 205 & meas.tech2 == 'wt' & app.mthd == 'os', ]
unique(x[, .(file, country)])
```

```{r}
x <- pdat[grepl('[Pp]edersen', submitter) & sub.period == 3, ]
unique(x[, file])

```








