
library(ALFAM2)
library(data.table)
library(ggplot2)
library(viridisLite)
library(knitr)
library(rmarkdown)
library(lme4)
library(doParallel)
library(doRNG)
library(R.utils)

sink('../logs/R-versions.txt')
  print(sessionInfo())
sink()
