---
title: 'Model call record'
output: pdf_document
classoption: landscape
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y %h:%m')`"
---

Check package version.

```{r}
packageVersion('ALFAM2')
```

Parameter values.

```{r}
ALFAM2pars02
```

Run model 

Subset 1 

```{r}
pars01 <- ALFAM2pars01[!grepl('man.ph', names(ALFAM2pars01))]
pars02 <- ALFAM2pars02[!grepl('man.ph', names(ALFAM2pars02))]
```

```{r}
d.pred1.ps1 <- as.data.table(alfam2(idat1, pars = pars01, app.name = 'tan.app', time.name = 'cta', group = 'pmid'))
d.pred1.ps2 <- as.data.table(alfam2(idat1, pars = pars02, app.name = 'tan.app', time.name = 'cta', group = 'pmid'))
```

```{r}
names(d.pred1.ps1)[-1:-3] <- paste0(names(d.pred1.ps1)[-1:-3], '.pred')
names(d.pred1.ps2)[-1:-3] <- paste0(names(d.pred1.ps2)[-1:-3], '.pred')

d.pred1.ps1$pars <- 'ps1'
d.pred1.ps2$pars <- 'ps2'

d1 <- cbind(idat1, d.pred1.ps1[, -1:-3])
d2 <- cbind(idat1, d.pred1.ps2[, -1:-3])
dpreds1 <- rbind(d1, d2)
```

Subset 2

```{r}
d.pred2.ps1 <- as.data.table(alfam2(idat2, pars = pars01, app.name = 'tan.app', time.name = 'cta', group = 'pmid'))
d.pred2.ps2 <- as.data.table(alfam2(idat2, pars = pars02, app.name = 'tan.app', time.name = 'cta', group = 'pmid'))
```

```{r}
names(d.pred2.ps1)[-1:-3] <- paste0(names(d.pred2.ps1)[-1:-3], '.pred')
names(d.pred2.ps2)[-1:-3] <- paste0(names(d.pred2.ps2)[-1:-3], '.pred')

d.pred2.ps1$pars <- 'ps1'
d.pred2.ps2$pars <- 'ps2'

d1 <- cbind(idat2, d.pred2.ps1[, -1:-3])
d2 <- cbind(idat2, d.pred2.ps2[, -1:-3])
dpreds2 <- rbind(d1, d2)
```

Subset 3

```{r}
d.pred3.ps1 <- as.data.table(alfam2(idat3, pars = pars01, app.name = 'tan.app', time.name = 'cta', group = 'pmid'))
d.pred3.ps2 <- as.data.table(alfam2(idat3, pars = pars02, app.name = 'tan.app', time.name = 'cta', group = 'pmid'))
```

```{r}
names(d.pred3.ps1)[-1:-3] <- paste0(names(d.pred3.ps1)[-1:-3], '.pred')
names(d.pred3.ps2)[-1:-3] <- paste0(names(d.pred3.ps2)[-1:-3], '.pred')

d.pred3.ps1$pars <- 'ps1'
d.pred3.ps2$pars <- 'ps2'

d1 <- cbind(idat3, d.pred3.ps1[, -1:-3])
d2 <- cbind(idat3, d.pred3.ps2[, -1:-3])
dpreds3 <- rbind(d1, d2)
```
