---
title: 'Subset summary'
output: pdf_document
classoption: landscape
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y %h:%m')`"
---

# Summary of main data subset

```{r}
nrow(pdat1)
```


```{r}
table(pdat1[, inst])
table(pdat1[, country])
table(pdat1[, .(inst, sub.period)])
table(pdat1[, .(institute, sub.period)])
table(pdat1[, man.source])
```

```{r}
table(pdat1[, digested])
table(pdat1[, .(institute, digested)])
names(pdat1)
table(pdat1[, .(sub.period, digested)])
table(pdat1[, .(sub.period, acid)])
table(pdat1[, .(institute, acid)])
table(pdat1[, .(sub.period, incorp)])
table(pdat1[, .(institute, incorp)])
```

```{r}
table(idat1[, rain.missing])
100 * mean(idat1[, rain.missing])

table(idat1[, interp.wind])
100 * mean(idat1[, interp.wind])

table(idat1[, interp.air.temp])
100 * mean(idat1[, interp.air.temp])

x <- unique(idat1[, .(inst, file, pmid, man.ph.missing, incorp)])
table(x[, man.ph.missing])
table(x[, .(inst, man.ph.missing)])
y <- x[(man.ph.missing), ]
table(y[, .(inst, incorp)])
100 * mean(x[, man.ph.missing])
```

```{r}
xx <- idat1[, any(rain.missing), by = pmid]
table(xx[, 2])
100 * mean(xx[, 2]$V1)

xx <- idat1[, any(interp.wind), by = pmid]
table(xx[, 2])
100 * mean(xx[, 2]$V1)

xx <- idat1[, any(interp.air.temp), by = pmid]
table(xx[, 2])
100 * mean(xx[, 2]$V1)

xx <- idat1[, any(man.ph.missing), by = pmid]
table(xx[, 2])
100 * mean(xx[, 2]$V1)
```

```{r}
table(pdat1$rain.12 == 0)
table(pdat1$rain.12 == 0) / nrow(pdat1)
```

```{r}
quantile(pdat1$rain.12 / 12, na.rm = TRUE)
x <- pdat1[rain.12 > 0, ]
quantile(x$rain.12 / 12, na.rm = TRUE)
range(x$rain.12 / 12, na.rm = TRUE)

x <- pdat1[rain.1 > 0, ]
quantile(x$rain.1, na.rm = TRUE)
range(x$rain.1, na.rm = TRUE)
```

```{r}
x <- idat1[rain.rate > 0, ]
quantile(x$rain.rate)
```

# Problems with incorporation

```{r}
table(pdati[, c('country', 'man.ph')])
table(pdati[, c('incorp', 'man.ph')])
```

Low pH for shallow incorp plots probably causing wrong sign for shallow incorp pars.

# Correlation among predictor variables

```{r}
m1 <- aov(man.dm ~ app.mthd, data = pdat1)
summary(m1)
TukeyHSD(m1)
model.tables(m1, 'means')
```

# dfsumm

```{r}
dfsumm(pdat1)
dfsumm(pdat2)
```

# Treatments

```{r}
pdat1[, man.trt.all := paste(man.trt1, man.trt2, man.trt3)]
table(pdat1[, man.trt.all])
```


